apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: employee-app

  template:
    metadata:
      labels:
        app: employee-app

    spec:
      containers:
        - name: employee-app
          image: sidhu9676/employee-app:v1

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"
